name: steno-reddit-leads

on:
  schedule:
    - cron: "0 13 * * *"   # runs daily at 9:00 AM ET (13:00 UTC)
  workflow_dispatch:        # lets you run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw

      - name: Run Reddit harvester
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python src/reddit_harvest.py
          ls -la data

      - name: Commit CSV output
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/leads_raw.csv"
          message: "Daily Reddit lead harvest"
